server:
  port: 8088
spring:
  application:
    name: my-demo

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mytest?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

abc:
  d: yse