/*
 Navicat Premium Data Transfer

 Source Server         : 路演
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 192.168.50.109:1521
 Source Schema         : TEST

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 13/06/2023 09:28:20
*/


-- ----------------------------
-- Table structure for LY_BASE_INFO
-- ----------------------------
DROP TABLE "luyan"."LY_BASE_INFO";
CREATE TABLE "luyan"."LY_BASE_INFO" (
  "PROJECT_ID" NUMBER(30,0) NOT NULL,
  "COMPANY_NAME" VARCHAR2(100 BYTE) NOT NULL,
  "SHORT_NAME" VARCHAR2(30 BYTE),
  "CREDIT_CODE" VARCHAR2(20 BYTE),
  "LEGAL_PERSON" VARCHAR2(100 BYTE) NOT NULL,
  "REGISTER_TIME" DATE,
  "REAL_CAPITAL" NUMBER(38,2) NOT NULL,
  "WEBSITE" VARCHAR2(50 BYTE),
  "AREA" VARCHAR2(50 BYTE) NOT NULL,
  "ADDRESS" VARCHAR2(50 BYTE),
  "LOGO" LONG NOT NULL,
  "LOGO_URL" VARCHAR2(255 BYTE),
  "TAGS" VARCHAR2(80 BYTE) NOT NULL,
  "REG_USER_NAME" VARCHAR2(100 BYTE) NOT NULL,
  "REG_USER_TITLE" VARCHAR2(100 BYTE) NOT NULL,
  "IS_REG_USER_MANAGER" CHAR(1 BYTE),
  "CONTACTS_PHONE" VARCHAR2(11 BYTE) NOT NULL,
  "CONTACTS_NAME" VARCHAR2(100 BYTE) NOT NULL,
  "CONTACTS_TITLE" VARCHAR2(100 BYTE) NOT NULL,
  "CONTACTS_EMAIL" VARCHAR2(100 BYTE) NOT NULL,
  "COMPANY_INFO" VARCHAR2(1000 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."PROJECT_ID" IS '项目id';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."COMPANY_NAME" IS '3、企业全称（companyName）不能为空且长度不超过100长度';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."SHORT_NAME" IS '4、企业简称（shortName），选填，可为空，长度不超过30长度';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."CREDIT_CODE" IS '社会统一信用代码(不能重复)';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."LEGAL_PERSON" IS '6、法定代表人（legalPerson）不为空且长度不超过100';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."REGISTER_TIME" IS '7、企业成立时间（registerTime）不能为空';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."REAL_CAPITAL" IS '14、注册资本（realCapital）单位：万元/人民币，不为空且整数15位以内且非0，可保留4位小数以内';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."WEBSITE" IS '企业网址';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."AREA" IS '15、所在地区（area），即省、市不为空，area字段须以”省份,市区”的格式填写';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."ADDRESS" IS '详细地址';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."LOGO" IS '5、企业logo与企业logoUrl是两种上传企业logo方式，logo可以传文件base64转码后的流，logoUrl可以传文件链接地址，两种方式选择一种即可，不能两个字段都为空';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."TAGS" IS '16、所属行业（tags）不为空，只能填写二级行业标签编号，行业标签编号中非0的就是二级行业标签，如有多个用英文逗号分割，例如：1,2,3';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."REG_USER_NAME" IS '8、注册人姓名（regUserName）不能为空且长度不超过100';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."REG_USER_TITLE" IS '9、注册人职务（regUserTitle）不能为空且长度不超过100';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."IS_REG_USER_MANAGER" IS '注册人是否为融资负责人(true(是),false(否)，选“是”，融资负责人手机号、姓名、职务这三个字段自动赋值)';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."CONTACTS_PHONE" IS '12、融资负责人手机（contactsPhone）不为空且长度为11位';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."CONTACTS_NAME" IS '10、融资负责人姓名（contactsName）不能为空且长度不超过100';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."CONTACTS_TITLE" IS '11、融资负责人职务（contactsTitle）不能为空且长度不超过100';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."CONTACTS_EMAIL" IS '13、联系人邮箱（contactsEmail）不为空；长度不超过100；符合邮箱格式；邮箱唯一';
COMMENT ON COLUMN "luyan"."LY_BASE_INFO"."COMPANY_INFO" IS '企业介绍';
COMMENT ON TABLE "luyan"."LY_BASE_INFO" IS '基本信息';

-- ----------------------------
-- Table structure for LY_BP_INFO
-- ----------------------------
DROP TABLE "luyan"."LY_BP_INFO";
CREATE TABLE "luyan"."LY_BP_INFO" (
  "PROJECT_ID" NUMBER(30,0) NOT NULL,
  "FILE" LONG,
  "FILE_PATH" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "luyan"."LY_BP_INFO"."FILE" IS '商业计划书(文件base64转码后的流（此处提供文件流和文件路径两种方式，根据实际情况选择一种即可）)';
COMMENT ON TABLE "luyan"."LY_BP_INFO" IS '商业计划书';

-- ----------------------------
-- Table structure for LY_CORE_TEAM_INFO
-- ----------------------------
DROP TABLE "luyan"."LY_CORE_TEAM_INFO";
CREATE TABLE "luyan"."LY_CORE_TEAM_INFO" (
  "PROJECT_ID" NUMBER(30,0) NOT NULL,
  "NAME" VARCHAR2(50 BYTE) NOT NULL,
  "TITLE" VARCHAR2(50 BYTE) NOT NULL,
  "EXPERIENCE" VARCHAR2(500 BYTE) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "luyan"."LY_CORE_TEAM_INFO"."NAME" IS '17、核心团队-姓名（name）不为空且不超过50长度';
COMMENT ON COLUMN "luyan"."LY_CORE_TEAM_INFO"."TITLE" IS '18、核心团队-职务名称（title）不为空且不超过50长度';
COMMENT ON COLUMN "luyan"."LY_CORE_TEAM_INFO"."EXPERIENCE" IS '19、核心团队-个人经历（experience）不为空且不超过500长度';
COMMENT ON TABLE "luyan"."LY_CORE_TEAM_INFO" IS '核心团队';

-- ----------------------------
-- Table structure for LY_FINANCE_DATA_INFO
-- ----------------------------
DROP TABLE "luyan"."LY_FINANCE_DATA_INFO";
CREATE TABLE "luyan"."LY_FINANCE_DATA_INFO" (
  "PROJECT_ID" NUMBER(30,0) NOT NULL,
  "TIME" VARCHAR2(20 BYTE),
  "INCOME" NUMBER(38,4),
  "NETPROFIT" NUMBER(38,4),
  "ASSETS" NUMBER(38,4),
  "LIABILITY" NUMBER(38,4)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "luyan"."LY_FINANCE_DATA_INFO"."INCOME" IS '营业收入(单位：万元/人民币)';
COMMENT ON COLUMN "luyan"."LY_FINANCE_DATA_INFO"."NETPROFIT" IS '净利润(单位：万元/人民币)';
COMMENT ON COLUMN "luyan"."LY_FINANCE_DATA_INFO"."ASSETS" IS '总资产(单位：万元/人民币)';
COMMENT ON COLUMN "luyan"."LY_FINANCE_DATA_INFO"."LIABILITY" IS '总负债(单位：万元/人民币)';
COMMENT ON TABLE "luyan"."LY_FINANCE_DATA_INFO" IS '财务指标';

-- ----------------------------
-- Table structure for LY_INVESTMENT_INFO
-- ----------------------------
DROP TABLE "luyan"."LY_INVESTMENT_INFO";
CREATE TABLE "luyan"."LY_INVESTMENT_INFO" (
  "PROJECT_ID" NUMBER(30,0) NOT NULL,
  "IS_INVESTMENT" VARCHAR2(255 BYTE),
  "INVESTMENT_STAGE" NUMBER,
  "INVESTMENT_TIME" DATE,
  "INVESTMENT_NAME" VARCHAR2(20 BYTE),
  "INVESTMENT_MONEY" NUMBER(38,2)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "luyan"."LY_INVESTMENT_INFO"."IS_INVESTMENT" IS '是否有融资成功经历,true（有）,false(没有)';
COMMENT ON COLUMN "luyan"."LY_INVESTMENT_INFO"."INVESTMENT_STAGE" IS '融资轮次（investmentStage）不为空';
COMMENT ON COLUMN "luyan"."LY_INVESTMENT_INFO"."INVESTMENT_TIME" IS '29、融资时间（investmentTime）不为空';
COMMENT ON COLUMN "luyan"."LY_INVESTMENT_INFO"."INVESTMENT_NAME" IS '30、投资机构（investmentName）不为空且不超过20长度';
COMMENT ON COLUMN "luyan"."LY_INVESTMENT_INFO"."INVESTMENT_MONEY" IS '31、融资金额（investmentMoney）不为空且不超过8长度（包括小数点），保留3位小数，单位：万元 / 人民币';
COMMENT ON TABLE "luyan"."LY_INVESTMENT_INFO" IS '融资经历';

-- ----------------------------
-- Table structure for LY_PROJECT_INFO
-- ----------------------------
DROP TABLE "luyan"."LY_PROJECT_INFO";
CREATE TABLE "luyan"."LY_PROJECT_INFO" (
  "ID" NUMBER(30,0) NOT NULL,
  "PROJECT_NAME" VARCHAR2(50 BYTE),
  "FINANCING_TYPE" VARCHAR2(30 BYTE),
  "NEED_MONEY" VARCHAR2(30 BYTE),
  "STAGE" NUMBER,
  "PROJECT_INFO" VARCHAR2(500 BYTE),
  "DEPT_CODE" VARCHAR2(20 BYTE),
  "SERVICE_ID" VARCHAR2(80 BYTE),
  "METHOD" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "luyan"."LY_PROJECT_INFO"."ID" IS 'id';
COMMENT ON COLUMN "luyan"."LY_PROJECT_INFO"."PROJECT_NAME" IS '项目名称';
COMMENT ON COLUMN "luyan"."LY_PROJECT_INFO"."FINANCING_TYPE" IS '24、融资方式（financingType）不为空,可多选，如果填写多个需用英文逗号分割，如：股权融资,债权融资';
COMMENT ON COLUMN "luyan"."LY_PROJECT_INFO"."NEED_MONEY" IS '拟融资金额:拉选项值：
100万以下，100-500万，500-1000万，1000-3000万，3000-5000万，5000万-1亿，1亿以上';
COMMENT ON COLUMN "luyan"."LY_PROJECT_INFO"."STAGE" IS '项目阶段';
COMMENT ON COLUMN "luyan"."LY_PROJECT_INFO"."PROJECT_INFO" IS '项目介绍（projectInfo）不为空；须超过100长度且不超过500长度';
COMMENT ON COLUMN "luyan"."LY_PROJECT_INFO"."DEPT_CODE" IS '部门代码';
COMMENT ON COLUMN "luyan"."LY_PROJECT_INFO"."METHOD" IS '融资路演注册:regProject
融资路演更新:updateProject
融资路演检查是否注册:checkRegInfo
融资路演获取审核状态:getUserCheckStatus
融资路演获取路演活动信息:getRoadshowApplyBySource';
COMMENT ON TABLE "luyan"."LY_PROJECT_INFO" IS '项目基本信息';

-- ----------------------------
-- Table structure for LY_REQUEST_ID
-- ----------------------------
DROP TABLE "luyan"."LY_REQUEST_ID";
CREATE TABLE "luyan"."LY_REQUEST_ID" (
  "PROJECT_ID" NUMBER(30,0) NOT NULL,
  "REQUEST_ID" NUMBER(38,0) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for LY_SHAREHOLDER_INFO
-- ----------------------------
DROP TABLE "luyan"."LY_SHAREHOLDER_INFO";
CREATE TABLE "luyan"."LY_SHAREHOLDER_INFO" (
  "PROJECT_ID" NUMBER(30,0) NOT NULL,
  "SHAREHOLDER_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "PROPORTION" VARCHAR2(20 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "luyan"."LY_SHAREHOLDER_INFO"."SHAREHOLDER_NAME" IS '股东姓名(20、不为空且不超过50长度)';
COMMENT ON COLUMN "luyan"."LY_SHAREHOLDER_INFO"."PROPORTION" IS '股权比例(21、不超过100%)';
COMMENT ON TABLE "luyan"."LY_SHAREHOLDER_INFO" IS '股权结构';

-- ----------------------------
-- Checks structure for table LY_BASE_INFO
-- ----------------------------
ALTER TABLE "luyan"."LY_BASE_INFO" ADD CONSTRAINT "SYS_C0015597" CHECK ("PROJECT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_BASE_INFO" ADD CONSTRAINT "SYS_C0015599" CHECK ("COMPANY_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_BASE_INFO" ADD CONSTRAINT "SYS_C0015600" CHECK ("LEGAL_PERSON" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_BASE_INFO" ADD CONSTRAINT "SYS_C0015601" CHECK ("LOGO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_BASE_INFO" ADD CONSTRAINT "SYS_C0015602" CHECK ("REAL_CAPITAL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_BASE_INFO" ADD CONSTRAINT "SYS_C0015603" CHECK ("AREA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_BASE_INFO" ADD CONSTRAINT "SYS_C0015604" CHECK ("TAGS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_BASE_INFO" ADD CONSTRAINT "SYS_C0015605" CHECK ("REG_USER_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_BASE_INFO" ADD CONSTRAINT "SYS_C0015606" CHECK ("REG_USER_TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_BASE_INFO" ADD CONSTRAINT "SYS_C0015607" CHECK ("CONTACTS_PHONE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_BASE_INFO" ADD CONSTRAINT "SYS_C0015608" CHECK ("CONTACTS_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_BASE_INFO" ADD CONSTRAINT "SYS_C0015609" CHECK ("CONTACTS_TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_BASE_INFO" ADD CONSTRAINT "SYS_C0015610" CHECK ("CONTACTS_EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table LY_BP_INFO
-- ----------------------------
ALTER TABLE "luyan"."LY_BP_INFO" ADD CONSTRAINT "SYS_C0015625" CHECK ("PROJECT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table LY_CORE_TEAM_INFO
-- ----------------------------
ALTER TABLE "luyan"."LY_CORE_TEAM_INFO" ADD CONSTRAINT "SYS_C0015611" CHECK ("PROJECT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_CORE_TEAM_INFO" ADD CONSTRAINT "SYS_C0015612" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_CORE_TEAM_INFO" ADD CONSTRAINT "SYS_C0015613" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_CORE_TEAM_INFO" ADD CONSTRAINT "SYS_C0015614" CHECK ("EXPERIENCE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table LY_FINANCE_DATA_INFO
-- ----------------------------
ALTER TABLE "luyan"."LY_FINANCE_DATA_INFO" ADD CONSTRAINT "SYS_C0015616" CHECK ("PROJECT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table LY_INVESTMENT_INFO
-- ----------------------------
ALTER TABLE "luyan"."LY_INVESTMENT_INFO" ADD CONSTRAINT "SYS_C0015619" CHECK ("PROJECT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table LY_PROJECT_INFO
-- ----------------------------
ALTER TABLE "luyan"."LY_PROJECT_INFO" ADD CONSTRAINT "SYS_C0015593" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table LY_PROJECT_INFO
-- ----------------------------
ALTER TABLE "luyan"."LY_PROJECT_INFO" ADD CONSTRAINT "SYS_C0015592" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table LY_PROJECT_INFO
-- ----------------------------
CREATE TRIGGER "luyan"."LY_PROJECT_INFO_ID_SEQ_TRG" BEFORE INSERT ON "luyan"."LY_PROJECT_INFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (NEW."ID" IS NULL) 
BEGIN
  SELECT ly_project_info_id_seq.NEXTVAL
  INTO :NEW."ID"
  FROM DUAL;
END;
/

-- ----------------------------
-- Checks structure for table LY_REQUEST_ID
-- ----------------------------
ALTER TABLE "luyan"."LY_REQUEST_ID" ADD CONSTRAINT "SYS_C0015627" CHECK ("PROJECT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_REQUEST_ID" ADD CONSTRAINT "SYS_C0015628" CHECK ("REQUEST_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table LY_REQUEST_ID
-- ----------------------------
CREATE UNIQUE INDEX "luyan"."PROJECT_ID_UNIQUE_IDX"
  ON "luyan"."LY_REQUEST_ID" ("PROJECT_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Checks structure for table LY_SHAREHOLDER_INFO
-- ----------------------------
ALTER TABLE "luyan"."LY_SHAREHOLDER_INFO" ADD CONSTRAINT "SYS_C0015617" CHECK ("PROJECT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "luyan"."LY_SHAREHOLDER_INFO" ADD CONSTRAINT "SYS_C0015618" CHECK ("SHAREHOLDER_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
