CREATE TABLE `sellfox_ad_sp_product_report`
(
    `id`                                varchar(36) NOT NULL,
    `create_by`                         varchar(50) DEFAULT NULL COMMENT '创建人',
    `create_time`                       datetime    DEFAULT NULL COMMENT '创建日期',
    `update_by`                         varchar(50) DEFAULT NULL COMMENT '更新人',
    `update_time`                       datetime    DEFAULT NULL COMMENT '更新日期',
    `task_name`                         varchar(50) DEFAULT NULL COMMENT '任务名称',
    `shop_ids`                          varchar(50) DEFAULT NULL COMMENT '店铺ID集合',
    `ad_type_code`                      varchar(50) DEFAULT NULL COMMENT '广告类型',
    `report_type_code`                  varchar(50) DEFAULT NULL COMMENT '报告类型',
    `report_cycle`                      varchar(50) DEFAULT NULL COMMENT '报告周期',
    `time_unit`                         varchar(50) DEFAULT NULL COMMENT '时间单位',
    `shop`                              varchar(50) DEFAULT NULL COMMENT '店铺',
    `date`                              varchar(20) DEFAULT NULL COMMENT '日期',
    `asin`                              varchar(50) default null comment 'asin',
    `sku`                               varchar(50) default null comment 'sku',
    `ad_group`                          varchar(50) default null comment '广告组',
    `ad_activity`                       varchar(50) default null comment '广告活动',
    `positioning_type`                  varchar(50) default null comment '定位类型',
    `ad_cost`                           varchar(50) default null comment '广告花费',
    `ad_exposure`                       varchar(50) default null comment '广告曝光量',
    `ad_hits`                           varchar(50) default null comment '广告点击量',
    `cpc`                               varchar(50) default null comment 'CPC',
    `ad_click_rate`                     varchar(50) default null comment '广告点击率',
    `ad_conversion_rate`                varchar(50) default null comment '广告转化率',
    `acos`                              varchar(50) default null comment 'ACoS',
    `roas`                              varchar(50) default null comment 'ROAS',
    `ad_order_quantity`                 varchar(50) default null comment '广告订单量',
    `order_quantity_of_this_ad_product` varchar(50) default null comment '本广告产品订单量',
    `ad_orders_for_other_products`      varchar(50) default null comment '其他产品广告订单量',
    `ad_sales_volume`                   varchar(50) default null comment '广告销售额',
    `sales_of_this_ad_product`          varchar(50) default null comment '本广告产品销售额',
    `ad_sales_of_other_products`        varchar(50) default null comment '其他产品广告销售额',
    `advertising_sales`                 varchar(50) default null comment '广告销量',
    `sales_volume_of_this_ad_product`   varchar(50) default null comment '本广告产品销量',
    `ad_sale_amount_of_other_products`  varchar(50) default null comment '其他产品广告销量',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='sellfox:SP广告——广告产品报告(sp-adProductReport)';
