server:
  port: 18082
spring:
  application:
    name: hailtaxi-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hailtaxi-order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    hikari:
      max-lifetime: 500000
  cloud:
    nacos:
      discovery:
        server-addr: 112.124.52.75:8848
        namespace: e1af5b3b-4fcb-4684-9289-549ff73b95d3
      config:
        server-addr: 112.124.52.75:8848
        namespace: e1af5b3b-4fcb-4684-9289-549ff73b95d3
        enabled: false

