CREATE TABLE `fund_cs`
(
    `id`                                    varchar(20) NOT NULL,
    `name`                                  varchar(50)          DEFAULT '' COMMENT '份额匿名名称',
    `publisher`                             varchar(50)          DEFAULT '' COMMENT '发布人',
    `industry`                              varchar(50)          DEFAULT '' COMMENT 'GICS行业',
    `type`                                  varchar(50)          DEFAULT '' COMMENT '基金类型',
    `manager`                               varchar(50)          DEFAULT '' COMMENT '管理人',
    `fund_currency_type`                    varchar(20)          DEFAULT '' COMMENT '基金货币类型',
    `order_deadline`                        varchar(10)          DEFAULT '' COMMENT '挂单期限',
    `fund_duration`                         varchar(20)          DEFAULT '' COMMENT '基金存续期',
    `total_fund_size`                       varchar(20)          DEFAULT '' COMMENT '基金总规模',
    `fund_cycle`                            varchar(20)          DEFAULT '' COMMENT '基金周期',
    `exit_cycle`                            varchar(20)          DEFAULT '' COMMENT '退出周期',
    `fund_type`                             varchar(50)          DEFAULT '' COMMENT '基金类型',
    `number_of_combined_companies`          varchar(10)          DEFAULT '' COMMENT '组合公司数量',
    `share_stage`                           varchar(50)          DEFAULT '' COMMENT '份额阶段',
    `fund_performance_fund_dpi`             varchar(50)          DEFAULT '' COMMENT '基金业绩 基金DPI',
    `fund_performance_fund_moic`            varchar(50)          DEFAULT '' COMMENT '基金业绩 基金MOIC',
    `fund_performance_fund_irr`             varchar(50)          DEFAULT '' COMMENT '基金业绩 基金IRR',
    `transfer_quota`                        varchar(20)          DEFAULT '' COMMENT '转让额度',
    `quotation_from_transferor`             varchar(20)          DEFAULT '' COMMENT '出让方报价',
    `transfer_discount`                     varchar(20)          DEFAULT '' COMMENT '转让折扣',
    `expected_buyer_type`                   varchar(20)          DEFAULT '' COMMENT '期望的买家类型',
    `reason_for_sale`                       varchar(20)          DEFAULT '' COMMENT '出售原因',
    `cooperate_with_due_diligence`          varchar(5)           DEFAULT '' COMMENT 'GP是否配合尽调',
    `introduction`                          varchar(20)          DEFAULT '' COMMENT '基金份额介绍',
    `special_transaction_currency`          varchar(20)          DEFAULT '' COMMENT '专项交易币种',
    `reason_for_special_sale`               varchar(20)          DEFAULT '' COMMENT '专项出售原因',
    `valuation_of_special_project_transfer` varchar(20)          DEFAULT '' COMMENT '专项项目转让估值',
    `special_exit_plan`                     varchar(20)          DEFAULT '' COMMENT '专项退出计划',
    `special_delivery_time_limit`           varchar(20)          DEFAULT '' COMMENT '专项交割时间期限',
    `special_fee_structure_management_fee`  varchar(20)          DEFAULT '' COMMENT '专项收费结构 管理费',
    `special_fee_structure_carry`           varchar(20)          DEFAULT '' COMMENT '专项收费结构 carry',
    `special_fee_structure_buyer_fa_fees`   varchar(20)          DEFAULT '' COMMENT '专项收费结构 买家FA费用',
    `create_time`                           datetime             DEFAULT NULL COMMENT '创建时间',
    `update_time`                           datetime             DEFAULT NULL COMMENT '更新时间',
    `create_by`                             varchar(20)          DEFAULT NULL COMMENT '创建人',
    `update_by`                             varchar(20)          DEFAULT NULL COMMENT '更新人',
    `deleted`                               bit(1)      NOT NULL DEFAULT b'0' COMMENT '删除标记（0：正常；1：已删除）',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='基金_晨哨';
