CREATE TABLE `sellfox_amazon_storage_data_report`
(
    `id`                               varchar(36) NOT NULL,
    `create_by`                        varchar(50)  DEFAULT NULL COMMENT '创建人',
    `create_time`                      datetime     DEFAULT NULL COMMENT '创建日期',
    `update_by`                        varchar(50)  DEFAULT NULL COMMENT '更新人',
    `update_time`                      datetime     DEFAULT NULL COMMENT '更新日期',
    `amz_report_id`                    varchar(50)  DEFAULT NULL COMMENT '报告ID',
    `shop_name`                        varchar(50)  DEFAULT NULL COMMENT '店铺名称',
    `report_type`                      varchar(50)  DEFAULT NULL COMMENT '报告类型',
    `report_time_range_str`            varchar(50)  DEFAULT NULL COMMENT '报告时间范围',
    `asin`                             varchar(50)  default null comment 'asin',
    `fnsku`                            varchar(50)  default null comment 'fnsku',
    `product_name`                     varchar(300) default null comment 'product_name',
    `fulfillment_center`               varchar(50)  default null comment 'fulfillment_center',
    `country_code`                     varchar(50)  default null comment 'country_code',
    `longest_side`                     varchar(50)  default null comment 'longest_side',
    `median_side`                      varchar(50)  default null comment 'median_side',
    `shortest_side`                    varchar(50)  default null comment 'shortest_side',
    `measurement_units`                varchar(50)  default null comment 'measurement_units',
    `weight`                           varchar(50)  default null comment 'weight',
    `weight_units`                     varchar(10)  default null comment 'weight_units',
    `item_volume`                      varchar(50)  default null comment 'item_volume',
    `volume_units`                     varchar(50)  default null comment 'volume_units',
    `average_quantity_on_hand`         varchar(50)  default null comment 'average_quantity_on_hand',
    `average_quantity_pending_removal` varchar(50)  default null comment 'average_quantity_pending_removal',
    `estimated_total_item_volume`      varchar(50)  default null comment 'estimated_total_item_volume',
    `month_of_charge`                  varchar(50)  default null comment 'month_of_charge',
    `storage_rate`                     varchar(50)  default null comment 'storage_rate',
    `currency`                         varchar(50)  default null comment 'currency',
    `estimated_monthly_storage_fee`    varchar(50)  default null comment 'estimated_monthly_storage_fee',
    `total_incentive_fee_amount`       varchar(50)  default null comment 'total_incentive_fee_amount',
    `breakdown_incentive_fee_amount`   varchar(50)  default null comment 'breakdown_incentive_fee_amount',
    `average_quantity_customer_orders` varchar(10)  default null comment 'average_quantity_customer_orders',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='sellfox:月仓储费报告';
