CREATE TABLE `sellfox_amazon_returns_data_report`
(
    `id`                    varchar(36) NOT NULL,
    `create_by`             varchar(50)  DEFAULT NULL COMMENT '创建人',
    `create_time`           datetime     DEFAULT NULL COMMENT '创建日期',
    `update_by`             varchar(50)  DEFAULT NULL COMMENT '更新人',
    `update_time`           datetime     DEFAULT NULL COMMENT '更新日期',
    `amz_report_id`         varchar(50)  DEFAULT NULL COMMENT '报告ID',
    `shop_name`             varchar(50)  DEFAULT NULL COMMENT '店铺名称',
    `report_type`           varchar(50)  DEFAULT NULL COMMENT '报告类型',
    `report_time_range_str` varchar(50)  DEFAULT NULL COMMENT '报告时间范围',
    `return_date`           varchar(50)  default null comment 'return-date',
    `order_id`              varchar(50)  default null comment 'order-id',
    `sku`                   varchar(50)  default null comment 'sku',
    `asin`                  varchar(50)  default null comment 'asin',
    `fnsku`                 varchar(50)  default null comment 'fnsku',
    `product_name`          varchar(300) default null comment 'product-name',
    `quantity`              varchar(50)  default null comment 'quantity',
    `fulfillment_center_id` varchar(50)  default null comment 'fulfillment-center-id',
    `detailed_disposition`  varchar(50)  default null comment 'detailed-disposition',
    `reason`                varchar(50)  default null comment 'reason',
    `license_plate_number`  varchar(10)  default null comment 'license-plate-number',
    `customer_comments`     varchar(50)  default null comment 'customer-comments',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='sellfox:每月库存历史记录';
