CREATE TABLE `sellfox_amazon_reimbursements_data_report`
(
    `id`                            varchar(36) NOT NULL,
    `create_by`                     varchar(50) DEFAULT NULL COMMENT '创建人',
    `create_time`                   datetime    DEFAULT NULL COMMENT '创建日期',
    `update_by`                     varchar(50) DEFAULT NULL COMMENT '更新人',
    `update_time`                   datetime    DEFAULT NULL COMMENT '更新日期',
    `amz_report_id`                 varchar(50) DEFAULT NULL COMMENT '报告ID',
    `shop_name`                     varchar(50) DEFAULT NULL COMMENT '店铺名称',
    `report_type`                   varchar(50) DEFAULT NULL COMMENT '报告类型',
    `report_time_range_str`         varchar(50) DEFAULT NULL COMMENT '报告时间范围',
    `approval_date`                 varchar(50) default null comment 'approval-date',
    `reimbursement_id`              varchar(50) default null comment 'reimbursement-id',
    `case_id`                       varchar(50) default null comment 'case-id',
    `amazon_order_id`               varchar(50) default null comment 'amazon-order-id',
    `reason`                        varchar(50) default null comment 'reason',
    `sku`                           varchar(50) default null comment 'sku',
    `fnsku`                         varchar(50) default null comment 'fnsku',
    `asin`                          varchar(50) default null comment 'asin',
    `product_name`                  varchar(50) default null comment 'product-name',
    `condition`                     varchar(50) default null comment 'condition',
    `currency_unit`                 varchar(50) default null comment 'currency-unit',
    `amount_per_unit`               varchar(50) default null comment 'amount-per-unit',
    `amount_total`                  varchar(50) default null comment 'amount-total',
    `quantity_reimbursed_cash`      varchar(50) default null comment 'quantity-reimbursed-cash',
    `quantity_reimbursed_inventory` varchar(50) default null comment 'quantity-reimbursed-inventory',
    `quantity_reimbursed_total`     varchar(50) default null comment 'quantity-reimbursed-total',
    `original_reimbursement_id`     varchar(50) default null comment 'original-reimbursement-id',
    `original_reimbursement_type`   varchar(50) default null comment 'original-reimbursement-type',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='sellfox:赔偿数量报告';
